# Generated by Django 2.2 on 2019-06-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Buty do kręgli', max_length=64, null=True)),
                ('stan', models.CharField(choices=[('3', 'Nowe'), ('2', 'Lekko zużyte'), ('1', 'Mocno zużyte'), ('0', 'Do wymiany')], max_length=1)),
                ('rozmiar', models.CharField(choices=[('32', 'Rozmiar 32'), ('33', 'Rozmiar 33'), ('34', 'Rozmiar 34'), ('35', 'Rozmiar 35'), ('36', 'Rozmiar 36'), ('37', 'Rozmiar 37'), ('38', 'Rozmiar 38'), ('39', 'Rozmiar 39'), ('40', 'Rozmiar 40'), ('41', 'Rozmiar 41'), ('42', 'Rozmiar 42'), ('43', 'Rozmiar 43'), ('44', 'Rozmiar 44'), ('45', 'Rozmiar 45'), ('46', 'Rozmiar 46'), ('47', 'Rozmiar 47'), ('48', 'Rozmiar 48'), ('49', 'Rozmiar 49')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Buty',
            },
        ),
        migrations.CreateModel(
            name='Przekaski',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('wycofana', models.BooleanField(default=False)),
                ('nazwa', models.CharField(max_length=64)),
                ('cena', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Przekąski',
            },
        ),
        migrations.CreateModel(
            name='Tor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('godzina_rozpoczecia', models.DateTimeField()),
                ('godzina_zakonczenia', models.DateTimeField()),
                ('nazwisko', models.CharField(max_length=64)),
                ('nr_toru', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tory',
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('nazwisko', models.CharField(max_length=64)),
                ('ilosc_osob', models.IntegerField()),
                ('tor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kregielnia_app.Tor')),
            ],
            options={
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
        migrations.CreateModel(
            name='PrzekaskiZamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('przekaski_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kregielnia_app.Przekaski')),
                ('rezerwacja_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kregielnia_app.Rezerwacja')),
            ],
            options={
                'verbose_name_plural': 'Przekąski Zamówienia',
            },
        ),
        migrations.CreateModel(
            name='ButyZamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('buty_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kregielnia_app.Buty')),
                ('rezerwacja_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kregielnia_app.Rezerwacja')),
            ],
            options={
                'verbose_name_plural': 'Przekąski Zamówienia',
            },
        ),
    ]
