# Generated by Django 2.2 on 2019-06-20 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kregielnia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='butyzamowienie',
            options={'verbose_name_plural': 'Buty Zamówienia'},
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulamin', models.BooleanField()),
                ('nr_telefonu_cc', models.CharField(max_length=5)),
                ('nr_telefonu', models.CharField(max_length=9)),
                ('newsletter', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
