# Generated by Django 2.2 on 2019-06-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kregielnia_app', '0002_auto_20190620_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='regulamin',
            field=models.BooleanField(default=False),
        ),
    ]
