# Generated by Django 2.2 on 2019-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kregielnia_app', '0003_auto_20190620_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='newsletter',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nr_telefonu',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nr_telefonu_cc',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='regulamin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
