# Generated by Django 2.1.7 on 2019-06-20 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kregielnia_app', '0004_auto_20190620_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Profile'},
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nr_telefonu_cc',
        ),
        migrations.RemoveField(
            model_name='rezerwacja',
            name='nazwisko',
        ),
        migrations.RemoveField(
            model_name='rezerwacja',
            name='tor_id',
        ),
        migrations.RemoveField(
            model_name='tor',
            name='godzina_rozpoczecia',
        ),
        migrations.RemoveField(
            model_name='tor',
            name='godzina_zakonczenia',
        ),
        migrations.RemoveField(
            model_name='tor',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='dt_rozpoczecia',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 18, 43, 22, 86351, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='dt_zakonczenia',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 18, 43, 24, 454486, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='user_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='kregielnia_app.Profil'),
            preserve_default=False,
        ),
    ]
