# Generated by Django 2.1.7 on 2019-06-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kregielnia_app', '0005_auto_20190620_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='dod_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='ilosc_godzin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='ilosc_torow',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
