# Generated by Django 2.2.2 on 2019-06-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kregielnia_app', '0006_auto_20190620_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butyzamowienie',
            name='buty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kregielnia_app.Buty'),
        ),
        migrations.AlterField(
            model_name='butyzamowienie',
            name='rezerwacja_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kregielnia_app.Rezerwacja'),
        ),
        migrations.AlterField(
            model_name='przekaskizamowienie',
            name='przekaski_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kregielnia_app.Przekaski'),
        ),
        migrations.AlterField(
            model_name='przekaskizamowienie',
            name='rezerwacja_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kregielnia_app.Rezerwacja'),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kregielnia_app.Profil'),
        ),
    ]
